[package]
name = "my_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.29.0"
egui-macroquad = "0.15.0"
macroquad = "0.4.13"
rand = { version = "0.8.5", features = ["std", "std_rng"] }
